FROM ghcr.io/twplatformlabs/circleci-base-image:ubuntu-latest

# awscli has to be pinned because the checkov package does not support more recent versions
ENV AWSCLI_VERSION=1.36.17
ENV RUBYOPT='-raws-sdk-elastictranscoder'
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

# Configured for automatic, monthly build using current package repository release versions.
# Pin downstream executor builds to specific OS and package versions using YYYY.MM tag.
# hadolint ignore=DL3004
RUN sudo apt-get update && sudo apt-get install --no-install-recommends -y \
                 nodejs \
                 npm \
                 ruby-full \
                 python3-dev \
                 python3-pip \
                 python3-venv \
                 yq && \
    sudo ln -f -s /usr/bin/pip3 /usr/bin/pip && \
    sudo ln -f -s /usr/bin/pydoc3 /usr/bin/pydoc && \
    sudo ln -f -s /usr/bin/python3 /usr/bin/python && \
    sudo ln -f -s /usr/bin/python3-config /usr/bin/python-config && \
    sudo pip install --no-cache-dir --break-system-packages --ignore-installed \
             awscli=="${AWSCLI_VERSION}" \
             checkov && \
    sudo npm install -g bats && \
    sudo gem install  --no-document \
             base64:0.1.0 \
             aws-sdk \
             aws-sdk-elastictranscoder \
             awspec \
             nokogiri \
             json && \
    sudo bash -c "curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm kubectl && \
    download_url=$(curl -s "https://api.github.com/repos/kubernetes-sigs/kind/releases/latest" | jq -r ".assets[] | select(.name == \"kind-linux-amd64\") | .browser_download_url") && \
    curl -Lo ./kind "${download_url}" && \
    sudo chmod +x ./kind && \
    sudo mv ./kind /usr/local/bin/kind && \
    sudo bash -c "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash" && \
    curl -o px https://storage.googleapis.com/pixie-dev-public/cli/latest/cli_linux_amd64 && \
    chmod +x px && sudo mv px /usr/local/bin/px && \
    curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && \
    sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd && \
    rm argocd-linux-amd64 && \
    sudo bash -c "curl -s https://fluxcd.io/install.sh | bash" && \
    download_url=$(curl -s "https://api.github.com/repos/twplatformlabs/circlepipe/releases/latest" | jq -r ".assets[] | select(.name == \"circlepipe_Linux_amd64.tar.gz\") | .browser_download_url") && \
    curl -LO "${download_url}" && \
    mkdir ./circlepipe && tar -xzf circlepipe_Linux_amd64.tar.gz -C ./circlepipe && \
    sudo mv ./circlepipe/circlepipe /usr/local/bin/circlepipe && \
    sudo rm -rf ./circlepipe circlepipe_Linux_amd64.tar.gz && \
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin && \
    download_url=$(curl -s https://api.github.com/repos/karmada-io/karmada/releases/latest | jq -r '.assets[] | select(.name == "karmadactl-linux-amd64.tgz") | .browser_download_url') && \
    curl -LO "${download_url}" && \
    sudo tar  --extract --gzip --file=karmadactl-linux-amd64.tgz -C /usr/local/bin karmadactl && \
    sudo chmod +x /usr/local/bin/karmadactl && rm karmadactl-linux-amd64.tgz

# hadolint ignore=DL3066
USER circleci

WORKDIR /home/circleci/project
